routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::post('login', ['uses' => "Admin\AuthController@postLogin", 'as' => 'postlogin']);
});

Route::get("login","Auth\LoginController@showLoginForm")->name("login");
Route::post("login","Auth\LoginController@login");

Route::group(["prefix"=>"demand","namespace"=>"Site"],function(){
    Route::get("/","DemandCont@index")->name("demand.index");
    Route::get("{id}/single","DemandCont@single")->name("demand.single");
//    Route::post("{id}/single","DemandCont@submit_offer")->name("demand.submit_offer");
});


Route::group(["middleware"=>"auth"],function(){
    Route::get("logout","Auth\LoginController@logout");
    Route::group(["namespace"=>"Dashboard","prefix"=>"dashboard"],function(){
        Route::group(["prefix"=>"userinfo","as"=>"userinfo."],function(){
            Route::get("/","UserInfoCont@index")->name("index");
            Route::post("/","UserInfoCont@update")->name("update");
        });

        Route::group(["prefix"=>"my-demand","as"=>"mydemand."],function(){
            Route::get("/","DemandCont@index")->name("index");
            Route::get("create","DemandCont@add")->name("create");
            Route::post("create","DemandCont@store")->name("store");
            Route::get("{id}/edit","DemandCont@edit")->name("edit");
            Route::post("{id}/edit","DemandCont@update")->name("update");
            Route::get("{id}/delete-attachment","DemandCont@remove_attachment")->name("delete_atachment");
            Route::get("{id}/delete","DemandCont@destroy")->name("delete");
            Route::get("offer-lists/{demand_id}","DemandCont@offer_list")->name("offer_lists");
            Route::post("give-offer/{demand_id}","DemandCont@give_offer")->name("give_offer");
        });

        Route::group(["prefix"=>"my-offer","as"=>"myoffer."],function(){
            Route::get("/","OfferCont@index")->name("index");
        });

        Route::group(["prefix"=>"my-company","as"=>"mycompany."],function(){
            Route::get("/","CompanyCont@index")->name("index");
            Route::post("/","CompanyCont@store")->name("store");
        });

        Route::group(["prefix"=>"my-message","as"=>"mymessage."],function(){
            Route::get("/","MessageCont@index")->name("index");
            Route::get("{message_id}/show","MessageCont@show")->name("show");
            Route::post("{message_id}/reply","MessageCont@reply")->name("reply");
            Route::post("send_message","MessageCont@send_message")->name("send_message");
        });

        Route::group(["prefix"=>"my-payment","as"=>"mypayment."],function(){
           Route::get("/","PaymentCont@index")->name("index");
           Route::get("{invoice_no}/detail","PaymentCont@detail")->name("detail");
        });
   });

    //pp
    Route::get("my-payment/{order_id}/status","PaypalCont@get_payment_status")->name("get_payment_status");
    Route::get("my-payment/{order_id}/pay-paypal","PaypalCont@pay_with_paypal")->name("pay_paypal");
});

app/Http/Controllers/Dashboard/CompanyCont.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Company;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CompanyCont extends Controller
{
    public function index(){
        $company = auth()->user()->company;
        return view("dashboard.company.index",compact("company"));
    }

    public function store(Request $request,Company $company){
        $validator = app("validator")->make($request->all(),[
            "name" => "required",
            "address" => "required"
        ]);

        if($validator->fails()){
            return back()->withErrors($validator->messages());
        }
        $request->merge(["user_id"=>$request->user()->id]);
        $store = $company->updateOrCreate(["id"=>$request->input("company_id")],$request->except(["logo","company_id","submit"]));

        if($request->hasFile("logo")){
            $store->uploadMedia($request->file("logo"),["width"=>300,"height"=>300]);
        }
        return back()->with(["success"=>"Company Saved."]);
    }
}

app/Http/Controllers/Dashboard/DemandCont.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Country;
use App\Models\Demand;
use App\Models\Offer;
use App\Models\Order;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Storage;

class DemandCont extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(){
        return view("dashboard.mydemand.index");
    }

    /**
     * @param Country $country
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function add(Country $country){
        $country = $country->newQuery()->pluck("name","id");
        return view("dashboard.mydemand.create",compact("country"));
    }

    /**
     * @param $id
     * @param Demand $demand
     * @param Country $country
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id,Demand $demand,Country $country){
        $demand = $demand->newQuery()->where("user_id",auth()->user()->id)->where("id",$id)->firstOrFail();
        $country = $country->newQuery()->pluck("name","id");
        return view("dashboard.mydemand.edit",compact("demand","country"));
    }

    /**
     * @param Request $request
     * @param Demand $demand
     * @param Order $order
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function store(Request $request,Demand $demand,Order $order){
        $validator = app("validator")->make($request->all(),[
            "title" => "required",
            "min_price" => "required|numeric",
            "max_price" => "required|numeric|min:".$request->input("min_price"),
            "country_id" => "required",
            "description" => "required",
            "doc" => "file|mimes:pdf"
        ]);

        if($validator->fails()){
            return back()->withErrors($validator->messages())->withInput()->with(["active"=>true]);
        }

        if($request->input("submit") == "draft"){
            $request->merge(["status"=>"draft"]);
        }else{
            if(setting("site.base_price") == 0){
                $request->merge(["status"=>"published"]);
            }else{
                $request->merge(["status"=>"pending"]);
            }

        }

        if($request->hasFile("doc_file")){
            $name = "attachment_".Carbon::now()->format("dmYHis").".pdf";
            $request->file("doc_file")->storeAs("public/attachment",$name);
            $request->merge(["doc"=>"public/attachment/{$name}"]);
        }

        $request->merge(["user_id"=>auth()->user()->id]);

        DB::beginTransaction();

        try{
            $d = $demand->newQuery()->create($request->except("submit","_token","doc_file"));
            DB::commit();
            if(setting("site.base_price") == 0){
                return redirect()->route("mydemand.index")->with(["success"=>"Demand Published"]);
            }

            $o = Order::create_order("demand",$d->id);
            return redirect()->route("mypayment.detail",["invoice_no"=>$o->invoice_no])->with(["success"=>"Need payment to publish your demand."]);;
        }catch (\Exception $e){
            try{
                DB::rollBack();
            }catch (\Exception $exception){
                return back()->withErrors(["failed"=>$exception->getMessage()]);
            }
        }


        return redirect()->route("mydemand.index")->with(["success"=>"Demand saved."]);
    }

    /**
     * @param $id
     * @param Request $request
     * @param Demand $demand
     * @param Order $order
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function update($id,Request $request,Demand $demand,Order $order){
        $d = $demand->newQuery()->findOrFail($id);
        $validator = app("validator")->make($request->all(),[
            "title" => "required",
            "min_price" => "required|numeric",
            "max_price" => "required|numeric|min:".$request->input("min_price"),
            "country_id" => "required",
            "description" => "required",
            "doc" => "file|mimes:pdf"
        ]);

        if($validator->fails()){
            return back()->withErrors($validator->messages())->withInput()->with(["active"=>true]);
        }

        if($request->input("submit") == "draft"){
            $request->merge(["status"=>"draft"]);
        }else{
            $request->merge(["status"=>"pending"]);
        }

        if($request->hasFile("doc_file")){
            Storage::delete($d->doc);
            $name = "attachment_".Carbon::now()->format("dmYHis").".pdf";
            $request->file("doc_file")->storeAs("public/attachment",$name);
            $request->merge(["doc"=>"public/attachment/{$name}"]);
        }

        $request->merge(["user_id"=>auth()->user()->id]);

        DB::beginTransaction();

        try{
            $d->update($request->except("submit","_token","doc_file"));

            $d = $demand->newQuery()->findOrFail($id);
            if($d->status == "pending"){
                $order->newQuery()->create([
                    "invoice_no" => "DEM".rand(1000000,9999999),
                    "payment_for" => "demand",
                    "amount" => setting("site.base_price",10),
                    "description" => "Payment for updating demand ".$d->title,
                    "status" => "pending",
                    "related_id" => $d->id
                ]);
            }

            DB::commit();

            if($d->status == "pending"){
                // TODO: Redirect to payment process
                return redirect()->route("mydemand.index")->with(["success"=>"Need payment."]);
            }
        }catch (\Exception $e){
            try{
                DB::rollBack();
            }catch (\Exception $exception){}
        }


        return redirect()->route("mydemand.index")->with(["success"=>"Demand saved."]);
    }

    /**
     * @param $id
     * @param Demand $demand
     * @return \Illuminate\Http\RedirectResponse
     */
    public function remove_attachment($id,Demand $demand){
        $demand = $demand->newQuery()->findOrFail($id);
        Storage::delete($demand->doc);
        return back()->with(["success"=>"attachment deleted"]);
    }

    /**
     * @param $id
     * @param Demand $demand
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id,Demand $demand){
        // TODO: Prevent demand with offer to be deleted
        $d = $demand->newQuery()->findOrFail($id);
        $d->delete();
        return back()->with(["success"=>"Deleted."]);
    }

    public function offer_list($id,Demand $demand){
        $demand = $demand->newQuery()->where("user_id",auth()->user()->id)->where("id",$id)->firstOrFail();

        $offers = $demand->offers()->latest()->orderBy("is_hired","desc")->paginate(10);

        return view("dashboard.mydemand.offer_lists",compact("offers","demand"));
    }

    public function hire($demand_id,$offer_id,Offer $offer){
        // set flag

        // notify to demand owner

        // notify to offer owner
    }

    public function give_offer($demand_id,Offer $offer,Request $request){
        if($demand_id == auth()->user()->id){
            abort(404);
        }
        $validator = app("validator")->make($request->all(),[
           "title" => "required",
           "description" => "required",
           "price" => "required"
        ]);

        if($validator->fails()){
            return back()->withErrors($validator->messages());
        }

        if($request->hasFile("doc_file")){
            $name = "offer_".Carbon::now()->format("dmYHis").".pdf";
            $request->file("doc_file")->storeAs("public/attachment/",$name);
            $request->merge(["doc"=>"public/attachment/".$name]);
        }

        $request->merge(["demand_id"=>$demand_id]);
        $request->merge(["status"=>setting("site.base_price") == 0 ? "published":"pending"]);
        $request->merge(["user_id"=>auth()->user()->id]);

        $store = $offer->create($request->except(["_token","doc_file"]));

        // redirect to payment
        if(setting("site.base_price") != 0){
            $o = Order::create_order("offer",$store->id);
            return redirect()->route("mypayment.detail",["invoice_no"=>$o->invoice_no]);
        }

        return redirect("dashboard/my-offer")->with(["success"=>"Offer created"]);

    }

}

app/Http/Controllers/Dashboard/MessageCont.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Message;
use DB;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MessageCont extends Controller
{
    public function index(Message $message){
        $messages = $message->newQuery()->where("receiver_id",auth()->user()->id)->orWhere("sender_id",auth()->user()->id)->latest()->get();
        return view("dashboard.mymessage.index",compact("messages"));
    }

    public function send_message(Request $request,Message $message){
        $receiver = $request->input("receiver_id");
        $body = $request->input("body");

        DB::beginTransaction();
        try{
            $message = $message->newQuery()->create([
                "sender_id" => auth()->user()->id,
                "receiver_id" => $receiver
            ]);

            $message->message_items()->create([
                "user_id" => auth()->user()->id,
                "body" => $body
            ]);
            DB::commit();
            return back()->with(["success"=>"Message Sent"]);
        }catch (\Exception $exception){
            DB::rollBack();
            return back()->withErrors(["failed"=>"Message not send"]);
        }
    }

    public function reply($message_id,Request $request,Message $message){
        $message = $message->newQuery()->findOrFail($message_id);

        $message->message_items()->create([
            "user_id" => auth()->user()->id,
            "body" => $request->input("body")
        ]);
        return back()->with(["success"=>"Message Sent"]);
    }

    public function show($message_id,Message $message){
        $messages = $message->newQuery()->findOrFail($message_id);
        if($messages->message_items()->count() > 0){
            $set = $messages->message_items()->where("user_id","!=",auth()->user()->id)->update(["is_read"=>1]);
        }
        $messages = $messages->message_items()->orderBy("created_at","asc")->get();
//        return $messages;
        return view("dashboard.mymessage.show",compact("messages","message_id"));
    }
}

app/Http/Controllers/Dashboard/OfferCont.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OfferCont extends Controller
{
    public function index(){
        return view("dashboard.myoffer.index");
    }
}

app/Http/Controllers/Dashboard/PaymentCont.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PaymentCont extends Controller
{
    public function index(){
        return view("dashboard.payment.index");
    }

    public function detail($invoice_no,Order $transaction){
        $transaction = $transaction->newQuery()->whereInvoiceNo($invoice_no)->firstOrFail();
        return view("dashboard.payment.detail",compact("transaction"));
    }
}

app/Http/Controllers/Dashboard/UserInfoCont.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Storage;

class UserInfoCont extends Controller
{
    public function index(){
        return view("dashboard.user_info.index");
    }

    public function update(Request $request){
        if($request->hasFile("avatar_file")){
            $path = "users/avatar/";
            $name = str_random(10).".".$request->file("avatar_file")->getClientOriginalExtension();
            Storage::delete(auth()->user()->avatar);
            $request->file("avatar_file")->storeAs("public/".$path,$name);
            $request->merge(["avatar"=>$path.$name]);
        }

        auth()->user()->update($request->only("skill","avatar","name"));
        return back()->with(["success"=>"Updated"]);

    }
}

resources/views/dashboard/mydemand/create.blade.php
@extends("master")

@push("on_body")
    @component("components.startpage",["breadcrumb"=>[route("mydemand.index")=>"My Demand","#"=>"Create"]])
        @slot("title")
            Create Demand
        @endslot
    @endcomponent

    <div class="jbm-emp-dashboard pad-xs-top-60">
        <div class="container">
            <div class="row margin-bottom-100">
                @widget("DashboardNav",["active"=>"my-demand"])

                <div class="col-md-9 col-sm-12 col-xs-12 pull-right">
                    <div class="job-history">
                        <h4>Create Demand</h4>
                        <span class="section-tit-line-2 margin-bottom-40"></span>

                        <div class="company-details margin-bottom-30 change-pass padding-bottom-60">
                            @include("partials.error")
                            <!-- row start -->
                            {!! Form::open(["class"=>"row","files"=>true]) !!}
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-group {{ session()->has("active") && session("active") == true ? "field-active":"" }}">
                                        {!! Form::text("title",null,["class"=>"form-control","id"=>"title","required"]) !!}
                                        {!! Form::label("title","Title") !!}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-group {{ session()->has("active") && session("active") == true ? "field-active":"" }} jbm-select-2">
                                        {!! Form::select("country_id",$country,null,["class"=>"jbm-s-salary jbm-select-hide-search","id"=>"jbm-s-business-type","placeholder"=>"Select Country"]) !!}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-group {{ session()->has("active") && session("active") == true ? "field-active":"" }}">
                                        {!! Form::number("min_price",null,["class"=>"form-control","id"=>"min_price","required"]) !!}
                                        {!! Form::label("min_price","Minimum Price") !!}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-group {{ session()->has("active") && session("active") == true ? "field-active":"" }}">
                                        {!! Form::number("max_price",null,["class"=>"form-control","id"=>"max_price","required"]) !!}
                                        {!! Form::label("max_price","Maximum Price") !!}
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group {{ session()->has("active") && session("active") == true ? "field-active":"" }}">
                                        {!! Form::textarea("description",null,["class"=>"form-control","id"=>"description","required","rows"=>"2"]) !!}
                                        {!! Form::label("description","Description") !!}
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group field-active">
                                        {!! Form::file("doc_file",["class"=>"form-control","id"=>"doc","required","style"=>"height:auto"]) !!}
                                        {!! Form::label("doc","Support Document (PDF)") !!}
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="text-right">
                                        <button name="submit" type="submit" value="draft" class="btn btn-primary">Save as Draft</button>
                                        <button name="submit" type="submit" value="publish" class="btn btn-primary">Next: Payment</button>
                                    </div>

                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endpush

resources/views/dashboard/mydemand/edit.blade.php
@extends("master")

@push("on_body")
    @component("components.startpage",["breadcrumb"=>[route("mydemand.index")=>"My Demand","#"=>"Create"]])
        @slot("title")
            Edit Demand
        @endslot
    @endcomponent

    <div class="jbm-emp-dashboard pad-xs-top-60">
        <div class="container">
            <div class="row margin-bottom-100">
                @widget("DashboardNav",["active"=>"my-demand"])

                <div class="col-md-9 col-sm-12 col-xs-12 pull-right">
                    <div class="job-history">
                        <h4>Edit Demand</h4>
                        <span class="section-tit-line-2 margin-bottom-40"></span>

                        <div class="company-details margin-bottom-30 change-pass padding-bottom-60">
                            @include("partials.error")
                            <!-- row start -->
                            {!! Form::model($demand,["class"=>"row","files"=>true]) !!}
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-group field-active">
                                        {!! Form::text("title",null,["class"=>"form-control","id"=>"title","required"]) !!}
                                        {!! Form::label("title","Title") !!}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-group field-active jbm-select-2">
                                        {!! Form::select("country_id",$country,null,["class"=>"jbm-s-salary jbm-select-hide-search","id"=>"jbm-s-business-type","placeholder"=>"Select Country"]) !!}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-group field-active">
                                        {!! Form::number("min_price",null,["class"=>"form-control","id"=>"min_price","required"]) !!}
                                        {!! Form::label("min_price","Minimum Price") !!}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-group field-active">
                                        {!! Form::number("max_price",null,["class"=>"form-control","id"=>"max_price","required"]) !!}
                                        {!! Form::label("max_price","Maximum Price") !!}
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group field-active">
                                        {!! Form::textarea("description",null,["class"=>"form-control","id"=>"description","required","rows"=>"2"]) !!}
                                        {!! Form::label("description","Description") !!}
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group field-active">
                                        {!! Form::file("doc_file",["class"=>"form-control","id"=>"doc","style"=>"height:auto"]) !!}
                                        {!! Form::label("doc","Support Document (PDF)") !!}
                                    </div>
                                    @if(Storage::exists($demand->doc))
                                    <span class="help-block"><a href="{{ Storage::url($demand->doc) }}">View current attachment file</a></span>
                                    <span class="help-block"><a href="{{ route("mydemand.delete_atachment",["id"=>$demand->id]) }}" onclick="return confirm('Are you sure?')">Delete current attachment file</a></span>
                                    @endif
                                </div>
                                <div class="col-xs-12">
                                    <div class="text-right">
                                        <button name="submit" type="submit" value="draft" class="btn btn-primary">Save as Draft</button>
                                        <button name="submit" type="submit" value="publish" class="btn btn-primary">Next: Payment</button>
                                    </div>

                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endpush

resources/views/dashboard/mydemand/index.blade.php
@extends("master")

@push("on_body")
    @component("components.startpage",["breadcrumb"=>["#"=>"My Demand"]])
        @slot("title")
            My Demand
        @endslot
    @endcomponent

    <div class="jbm-emp-dashboard pad-xs-top-60">
        <div class="container">
            <div class="row margin-bottom-100">
                @widget("DashboardNav",["active"=>"my-demand"])

                <div class="col-md-9 col-sm-12 col-xs-12 pull-right">

                    <div class="job-history">
                        <h4>My Demand</h4>
                        <span class="section-tit-line-2 margin-bottom-20"></span>
                        <div class="text-right margin-bottom-20">
                            @include("partials.error")
                            @include("partials.success")
                            <a href="{{ route("mydemand.create") }}" class="btn btn-primary">Create new demand</a>
                        </div>
                        @widget("MyDemand")
                    </div>
                </div>

            </div>
        </div>
    </div>

@endpush