routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::post('login', ['uses' => "Admin\AuthController@postLogin", 'as' => 'postlogin']);
});

Route::get("login","Auth\LoginController@showLoginForm")->name("login");
Route::post("login","Auth\LoginController@login");

Route::group(["prefix"=>"demand","namespace"=>"Site"],function(){
    Route::get("/","DemandCont@index")->name("demand.index");
    Route::get("{id}/single","DemandCont@single")->name("demand.single");
//    Route::post("{id}/single","DemandCont@submit_offer")->name("demand.submit_offer");
});


Route::group(["middleware"=>"auth"],function(){
    Route::get("logout","Auth\LoginController@logout");
    Route::group(["namespace"=>"Dashboard","prefix"=>"dashboard"],function(){
        Route::group(["prefix"=>"userinfo","as"=>"userinfo."],function(){
            Route::get("/","UserInfoCont@index")->name("index");
            Route::post("/","UserInfoCont@update")->name("update");
        });

        Route::group(["prefix"=>"my-demand","as"=>"mydemand."],function(){
            Route::get("/","DemandCont@index")->name("index");
            Route::get("create","DemandCont@add")->name("create");
            Route::post("create","DemandCont@store")->name("store");
            Route::get("{id}/edit","DemandCont@edit")->name("edit");
            Route::post("{id}/edit","DemandCont@update")->name("update");
            Route::get("{id}/delete-attachment","DemandCont@remove_attachment")->name("delete_atachment");
            Route::get("{id}/delete","DemandCont@destroy")->name("delete");
            Route::get("offer-lists/{demand_id}","DemandCont@offer_list")->name("offer_lists");
            Route::post("give-offer/{demand_id}","DemandCont@give_offer")->name("give_offer");
        });

        Route::group(["prefix"=>"my-offer","as"=>"myoffer."],function(){
            Route::get("/","OfferCont@index")->name("index");
        });

        Route::group(["prefix"=>"my-company","as"=>"mycompany."],function(){
            Route::get("/","CompanyCont@index")->name("index");
            Route::post("/","CompanyCont@store")->name("store");
        });

        Route::group(["prefix"=>"my-message","as"=>"mymessage."],function(){
            Route::get("/","MessageCont@index")->name("index");
            Route::get("{message_id}/show","MessageCont@show")->name("show");
            Route::post("{message_id}/reply","MessageCont@reply")->name("reply");
            Route::post("send_message","MessageCont@send_message")->name("send_message");
        });

        Route::group(["prefix"=>"my-payment","as"=>"mypayment."],function(){
           Route::get("/","PaymentCont@index")->name("index");
           Route::get("{invoice_no}/detail","PaymentCont@detail")->name("detail");
        });
   });

    //pp
    Route::get("my-payment/{order_id}/status","PaypalCont@get_payment_status")->name("get_payment_status");
    Route::get("my-payment/{order_id}/pay-paypal","PaypalCont@pay_with_paypal")->name("pay_paypal");
});

resources/views/widgets/dashboard_nav.blade.php
<!-- Emp sidebar -->
<div class="col-md-3 col-sm-12 col-xs-12">
    <div class="jbm-emp-sidebar padding-bottom-30 padding-top-30">
        <ul class="jbm-dashboard-links">
            @foreach($config["list"] as $list)
                <li>
                    <a href="{{ $list["url"] }}" class="{{ $list["slug"]== $config["active"] ? 'active':'' }}">{{ $list["text"]}}</a>
                </li>
            @endforeach
        </ul>
    </div>
</div>

resources/views/widgets/demand_item.blade.php
<div class="jbm-job-loop-in">
    <div class="row">
        <div class="col-md-3 col-sm-5 col-xs-5 full-wdth mg-btm-20 text-left jbm-first-col">
            <div class="row">
                <div class="col-xs-4">
                    <div class="jbm-company-logo">
                        @if($config["logo"] == null)
                            {{ strtoupper(substr($config["title"],0,1)) }}
                        @else
                            <img src="{{ $config["logo"] }}" alt="{{ strtoupper($config['title']) }}" style="width: 80px;">
                        @endif
                    </div>
                </div>
                <div class="col-xs-8">
                    <div class="jbm-job-title">
                        <a href="#" class="title-link">{{ $config["title"] }}</a>
                        <br />
                        <a href="#" class="jbm-job-email">@ {{ $config["company_name"] }}</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 col-sm-2 col-xs-4 text-center">
            <div class="jbm-job-locaction">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <br />
                <a href="#">{{ $config["city_name"] }}</a>
            </div>
        </div>
        <div class="col-md-4 col-sm-5 col-xs-8 text-center">
            <div class="jbm-job-price">
                <i class="fa fa-money" aria-hidden="true"></i>
                <br />
                <span>{{ $config["min_price"] }} - {{ $config["max_price"] }}</span>
            </div>
        </div>
        <div class="col-md-3 col-xs-12 col-xs-12 text-center">
            <div class="jbm-job-links">
                <div class="jbm-job-detail">
                    <a href="{{ route("demand.single",["id"=>$config["id"]]) }}">Demand Detail</a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/widgets/home_search.blade.php
<!-- start search -->
<div class="jbm-search-bar jbm-search-1">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="jbm-sch-inner margin-top-85-minus">
                    <form class="row" method="get">
                        <div class="col-md-6 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <input value="{{ Request::get("keywords") }}" type="text" class="form-control" id="keyword" name="keywords" placeholder="Search Your Keyword" />
                                {{--<p>(Example: web design, seo analyst)</p>--}}
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="form-group">
                                {!! Form::select("country",$country,Request::get("country"),["class"=>"form-control","id"=>"location","placeholder"=>"Select Country"]) !!}
                                {{--<input type="text" class="form-control" id="location" name="country" placeholder="Location" />--}}
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="form-group ">
                                <input type="submit" class="jbm-button jbm-button-3" id="search-btn" />
                                {{--<p class="text-center"><a href="#">More Search Options</a></p>--}}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end search -->

resources/views/widgets/latest_job.blade.php
<!-- end section category -->
<div class="jbm-section-jobs padding-top-80 padding-bottom-100">
    <div class="container">
        <div class="row">
            @foreach($demands as $demand)
                @widget("DemandItem",[
                "logo" => $demand->logo,
                "company_name" => $demand->user->company->name ?? $demand->user->name,
                "city_name" => $demand->country->name ?? "Unknown",
                "title" => $demand->title,
                "min_price" => $demand->min_price,
                "max_price" => $demand->max_price,
                "id" => $demand->id,
                ])
            @endforeach
        </div>
    </div>
</div>

resources/views/widgets/my_demand.blade.php
<div class="job-posted padding-bottom-20 table-sm-setting">
    <div class="row margin-bottom-20">
        <div class="col-xs-3">
            <strong class="margin-bottom-20">Title</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-1 text-center">
            <strong class="margin-bottom-20">Country</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-2 text-center">
            <strong class="margin-bottom-20">Price (USD)</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-3">
            <strong class="margin-bottom-20">Description</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-1">
            <strong class="margin-bottom-20 text-center">Offers</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-1">
            <strong class="margin-bottom-20">Status</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-1">
        </div>
    </div>
    @forelse($demands as $demand)
        <div class="row margin-bottom-40">
        <div class="col-xs-3 demand-title">
            <span class="margin-bottom-20">
                <a href="#">
                    {{ $demand->title }}
                </a>
                <br>
                @if($demand->offers()->count() == 0)
                <small class="act hidden"> <a href="{{ route("mydemand.edit",["id"=>$demand->id]) }}">Edit</a></small>
                @endif
            </span>
        </div>
        <div class="col-xs-1 text-center">
            <span class="margin-bottom-20">{{ $demand->country->code ?? 0 }}</span>
        </div>
        <div class="col-xs-2 text-center">
            <span class="margin-bottom-20">
                {{ $demand->min_price ?? 0 }} - {{ $demand->max_price ?? 0 }}
            </span>
        </div>
        <div class="col-xs-3">
            <span class="margin-bottom-20">{{ $demand->short_description }}</span>
        </div>
        <div class="col-xs-1 text-center">
            <span class="margin-bottom-20"><a href="{{ route("mydemand.offer_lists",["demand_id"=>$demand->id]) }}">{{ $demand->offers()->count() }}</a></span>
        </div>
        <div class="col-xs-1">
            <span class="margin-bottom-20">{{ $demand->status }}</span>
        </div>
        <div class="col-xs-1 text-right">
            <span class="margin-bottom-20">
                @if($demand->offers()->count() == 0)
                <a onclick="return confirm('Delete {{ $demand->title }} ?')" href="{{ route("mydemand.delete",["id"=>$demand->id]) }}" class="fa fa-trash"></a>
                @endif
            </span>
        </div>
        </div>
        @empty
            <div class="text-center">
                No demand.
            </div>
    @endforelse
    <div class="text-center">
        {!! $demands->render() !!}
    </div>
</div>

@push("scripts")
    <script>
        $(document).on("mouseover",".demand-title",function(){
             $(this).find(".act").toggleClass("hidden");
        });

        $(document).on("mouseout",".demand-title",function(){
            $(this).find(".act").toggleClass("hidden");
        });
    </script>
@endpush

resources/views/widgets/my_offer.blade.php
<div class="job-posted padding-bottom-20 table-sm-setting">
    <div class="row margin-bottom-20">
        <div class="col-md-3 col-sm-4 col-xs-2">
            <strong class="margin-bottom-20">Demand</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-md-3 col-sm-4 col-xs-2">
            <strong class="margin-bottom-20">Budget</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-2">
            <strong class="margin-bottom-20">Offer Price</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-md-2 col-sm-3 col-xs-2">
            <strong class="margin-bottom-20">Offer Date</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-md-1 col-sm-1 col-xs-2">
            <strong class="margin-bottom-20">Status</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-md-1 col-sm-1 col-xs-2">
        </div>
    </div>
    @forelse($offers as $offer)
        <div class="row margin-bottom-40">
            <div class="col-md-3 col-sm-4 col-xs-2">
                <span class="margin-bottom-20">
                    <a href="{{ route("demand.single",["id"=>$offer->demand->id]) }}">
                        {{ $offer->demand->title }}
                    </a>
                    &nbsp;
                    <a href="#" class="btn btn-xs {{ $offer->count() > 0 ? "btn-info":"btn-default" }}" style="padding: 1px 8px;"><i class="fa fa-envelope"></i></a>

                </span>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-2">
                <span class="margin-bottom-20">${{ $offer->demand->min_price }} - ${{ $offer->demand->max_price }}</span>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-2">
                <span class="margin-bottom-20">${{ $offer->price }}</span>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-2">
                <span class="margin-bottom-20">{{ $offer->created_at->format("d M Y") }}</span>
            </div>
            <div class="col-md-1 col-sm-1 col-xs-2">
                <span class="margin-bottom-20">{{ $offer->status }}</span>
            </div>
            <div class="col-md-1 col-sm-1 col-xs-2"></div>
        </div>
        @empty
            <div class="text-center">
                No Offer
            </div>
    @endforelse
    <div class="text-center">
        {!! $offers->render() !!}
    </div>

</div><!--job-posted end-->

resources/views/widgets/my_payment.blade.php
<div class="job-posted padding-bottom-20 table-sm-setting">
    <div class="row margin-bottom-20">
        <div class="col-xs-2">
            <strong class="margin-bottom-20">Invoice No.</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-1 text-center">
            <strong class="margin-bottom-20">Status</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-2 text-center">
            <strong class="margin-bottom-20">Type</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-3">
            <strong class="margin-bottom-20">Description</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        <div class="col-xs-3">
            <strong class="margin-bottom-20">Message</strong>
            <span class="section-tit-line-2 margin-bottom-40"></span>
        </div>
        {{--<div class="col-xs-1">--}}
        {{--</div>--}}
    </div>
    @forelse($transactions as $transaction)
        <div class="row margin-bottom-40">
            <div class="col-xs-2">
                <span class="margin-bottom-20">
                    <a href="{{ route("mypayment.detail",["invoice_no"=>$transaction->invoice_no]) }}">{{ $transaction->invoice_no }}</a><br>
                </span>
            </div>
            <div class="col-xs-1">
            <span class="margin-bottom-20">
                {{ $transaction->status }}
            </span>
            </div>
            <div class="col-xs-2 text-center">
                <span class="margin-bottom-20">{{ $transaction->payment_for }}</span>
            </div>
            <div class="col-xs-3">
                <span class="margin-bottom-20">{{ $transaction->description }}</span>
            </div>
            <div class="col-xs-3">
                <span class="margin-bottom-20">{{ $transaction->message ?? "-" }}</span>
            </div>
            {{--<div class="col-xs-1 text-right">--}}
            {{--<span class="margin-bottom-20">--}}
                {{--<a onclick="return confirm('Delete {{ $transaction->title }} ?')" href="#" class="fa fa-trash"></a>--}}
            {{--</span>--}}
            {{--</div>--}}
        </div>
    @empty
        <div class="text-center">
            No Payment.
        </div>
    @endforelse
    <div class="text-center">
        {!! $transactions->render() !!}
    </div>
</div>

@push("scripts")
    <script>
        $(document).on("mouseover",".demand-title",function(){
            $(this).find(".act").toggleClass("hidden");
        });

        $(document).on("mouseout",".demand-title",function(){
            $(this).find(".act").toggleClass("hidden");
        });
    </script>
@endpush

resources/views/widgets/partners.blade.php
@if($partners->count() > 0)
    @include("partials.partners_title")

    <div class="jbm-section-partners padding-bottom-85">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <ul class="list-none dis-inline jbm-partner-list">
                        @foreach($partners as $partner)
                            <li class="jbm-partner-box">
                                <a href="{{ $partner->url }}">
                                    <img src="{{ Voyager::image($partner->image) }}" alt="{{ $partner->name }}" />
                                </a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>

@endif